{% set name = "quasiqueue" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quasiqueue-{{ version }}.tar.gz
  sha256: 53eb91a1a4f79e0d0eee7d9b8be37543a74de16988f6e0d47d818528358fbe55

build:
  entry_points:
    - quasiqueue = quasiqueue.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=67.0
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.10
    - psutil
    - pydantic >=2.0,<3.dev0
    - pydantic-settings
    - typer >=0.9.0

test:
  imports:
    - quasiqueue
  commands:
    - pip check
    - quasiqueue --help
  requires:
    - pip

about:
  home: https://github.com/tedivm/quasiqueue
  summary: A Simple High Performance Multiprocess Queue
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
