{% set name = "quasiqueue" %}
{% set version = "0.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quasiqueue-{{ version }}.tar.gz
  sha256: c8a97c30e2c975383101b887e54f829d64e26a45c233d8d76fb6a6c5024c5815

build:
  entry_points:
    - quasiqueue = quasiqueue.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.0
    - setuptools-scm >=7.1
    - pip
  run:
    - python >={{ python_min }}
    - psutil
    - pydantic >=2.0,<3.dev0
    - pydantic-settings
    - typer >=0.9.0

test:
  imports:
    - quasiqueue
  commands:
    - pip check
    - quasiqueue --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tedivm/quasiqueue
  summary: A Simple High Performance Multiprocess Queue
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
